language: cpp
compiler: gcc

notifications:
  irc:
    channels:
      - "chat.freenode.net#openbts"
    template:
      - "%{repository} : %{message} : %{build_url}"
    on_success: change
    on_failure: always

before_install:
 - sudo apt-get install -qq libssl-dev unixodbc-dev libsrtp0 libsrtp0-dev

#install:
#  - sh bootstrap.sh

script:
 - ./build.sh

